<?php

namespace App\Enums;

abstract class AccidentRepairStatusEnum
{
    const WAITING_APPROVE_REPAIR_LIST = 'WAITING_APPROVE_REPAIR_LIST';
    const WAITING_CRADLE_QUOTATION = 'WAITING_CRADLE_QUOTATION';
    const WAITING_APPROVE_REPAIR = 'WAITING_APPROVE_REPAIR';
    const WAITING_APPROVE_REPAIR_TTL = 'WAITING_APPROVE_REPAIR_TTL';
    const PROCESS_REPAIR = 'PROCESS_REPAIR';
    const SUCCESS_REPAIR = 'SUCCESS_REPAIR';
    const TTL = 'TTL';
    const OFFER_NEW_PRICE = 'OFFER_NEW_PRICE';

    const CONFIRM = 'CONFIRM';
    const REJECT = 'REJECT';
}
