<?php

namespace App\Enums;

abstract class AccidentRepairFollowUpStatusEnum
{
    const WAITING_SEND_REPAIR = 'WAITING_SEND_REPAIR';
    const PREPARE_BID = 'PREPARE_BID';
    const WAITING_INSURANCE_APPROVE = 'WAITING_INSURANCE_APPROVE';
    const WAITING_SPARE_PART = 'WAITING_SPARE_PART';
    const PART_BO = 'PART_BO';
    const UNDER_REPAIR_PREPARE_KNOCK = 'UNDER_REPAIR_PREPARE_KNOCK';
    const UNDER_REPAIR_KNOCK = 'UNDER_REPAIR_KNOCK';
    const UNDER_REPAIR_PREPARE_PUTTY = 'UNDER_REPAIR_PREPARE_PUTTY';
    const UNDER_REPAIR_PUTTY = 'UNDER_REPAIR_PUTTY';
    const UNDER_REPAIR_PREPARE_GROUND_COLOR = 'UNDER_REPAIR_PREPARE_GROUND_COLOR';
    const UNDER_REPAIR_GROUND_COLOR = 'UNDER_REPAIR_GROUND_COLOR';
    const UNDER_REPAIR_PREPARE_TRUE_COLOR = 'UNDER_REPAIR_PREPARE_TRUE_COLOR';
    const UNDER_REPAIR_TRUE_COLOR = 'UNDER_REPAIR_TRUE_COLOR';
    const UNDER_REPAIR_PREPARE_ATTRITION = 'UNDER_REPAIR_PREPARE_ATTRITION';
    const UNDER_REPAIR_ATTRITION = 'UNDER_REPAIR_ATTRITION';
    const UNDER_REPAIR_ASSEMBLE = 'UNDER_REPAIR_ASSEMBLE';
    const UNDER_REPAIR_CHECK_QUALITY = 'UNDER_REPAIR_CHECK_QUALITY';
    const SUCCESS = 'SUCCESS';
}
