<?php

namespace App\Enums;

abstract class ConfigApproveTypeEnum
{
    const PURCHASE_REQUISITION = 'PURCHASE_REQUISITION';
    const PURCHASE_ORDER = 'PURCHASE_ORDER';
    const LT_SPEC_ACCESSORY = 'LT_SPEC_ACCESSORY';
    const LT_QUOTATION_AFFILIATED = 'LT_QUOTATION_AFFILIATED';
    const LT_QUOTATION_UNAFFILIATED = 'LT_QUOTATION_UNAFFILIATED';
    const EQUIPMENT_ORDER = 'EQUIPMENT_ORDER';
    const REPLACEMENT_CAR = 'REPLACEMENT_CAR';
    const BORROW_CAR = 'BORROW_CAR';
    const REPAIR_ORDER = 'REPAIR_ORDER';
    const ACCIDENT_REPAIR_ORDER = 'ACCIDENT_REPAIR_ORDER';
    const ACCIDENT_REPAIR_ORDER_SHEET = 'ACCIDENT_REPAIR_ORDER_SHEET';
    const ACCIDENT_REPAIR_ORDER_SHEET_TTL = 'ACCIDENT_REPAIR_ORDER_SHEET_TTL';
    const SELLING_PRICE = 'SELLING_PRICE';
    const FINANCE_REQUEST = 'FINANCE_REQUEST';
    const LITIGATION = 'LITIGATION';
    const COMPENSATION = 'COMPENSATION';
}
