<?php

namespace App\Enums;

abstract class DepartmentEnum
{
    const QMD_QUALITY_ASSURANCE = 'QMD_QUALITY_ASSURANCE';
    const QMD_MAINTENANCE = 'QMD_MAINTENANCE';
    const CSD_CUSTOMER_SERVICE_CORPORATE = 'CSD_CUSTOMER_SERVICE_CORPORATE';
    const PCD_SALE = 'PCD_SALE';
    const PCD_PURCHASE = 'PCD_PURCHASE';
    const PCD_PREPARE_FINANCE = 'PCD_PREPARE_FINANCE';
    const PCD_INSTALL_EQUIPMENT = 'PCD_INSTALL_EQUIPMENT';
    const PCD_REGISTRATION = 'PCD_REGISTRATION';
    const PCD_GPS_MANAGEMENT = 'PCD_GPS_MANAGEMENT';
    const PCD_RESALE = 'PCD_RESALE';
    const AMO_SALE_ADMIN = 'AMO_SALE_ADMIN';
    const AMO_TRANSPORT = 'AMO_TRANSPORT';
    const AMO_PETTY_CASH_MANAGEMENT = 'AMO_PETTY_CASH_MANAGEMENT';
    const AMO_LONGTERM_AFFILIATES = 'AMO_LONGTERM_AFFILIATES';
    const FOD_FINANCE_SUPPORT = 'FOD_FINANCE_SUPPORT';
    const FOD_MAINTENANCE_SERVICE_SUPPORT = 'FOD_MAINTENANCE_SERVICE_SUPPORT';
    const FMD_FEET_MANAGEMENT = 'FMD_FEET_MANAGEMENT';
    const RMD_LEGAL = 'RMD_LEGAL';
    const RMD_INSURANCE = 'RMD_INSURANCE';
    const RMD_CONTRACT = 'RMD_CONTRACT';
    const RMD_ACCIDENT = 'RMD_ACCIDENT';
    const CMD_LONGTERM_RENTAL = 'CMD_LONGTERM_RENTAL';
    const CMD_SHORTTERM_RENTAL = 'CMD_SHORTTERM_RENTAL';
    const FAD_COLLECTION = 'FAD_COLLECTION';
    const FAD_ASSET = 'FAD_ASSET';
    const FAD_ACCOUNTS_RECEIVABLE = 'FAD_ACCOUNTS_RECEIVABLE';
    const FAD_FINANCE_RECEIPT = 'FAD_FINANCE_RECEIPT';
    const FAD_ACCOUNT_PAYABLE = 'FAD_ACCOUNT_PAYABLE';
    const BMD_BRANCH_MANAGEMENT = 'BMD_BRANCH_MANAGEMENT';
    const ADMIN = 'ADMIN';
}
